# Execute a try block, except block, and finally block.
try:
  print(x)
except:
  print("Something went wrong")
finally:
  print("The 'try except' is finished")
